### ISSUE TITLE
refresh_puid reponse has changed?

### ISSUE THREAD

**Issue by WeldFire** [daan-dj/TurboGpt#4]
Great looking implementation, thank you for making and sharing it with the world!

When following the setup process and attempting to start a session I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\turbogpt\turbogpt.py", line 33, in __init__
    self.refresh_puid()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\turbogpt\turbogpt.py", line 43, in refresh_puid
    self.session.cookies["_puid"] = res.cookies["_puid"]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tls_client\cookies.py", line 261, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tls_client\cookies.py", line 340, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='_puid', domain=None, path=None"
```

When printing out the cookie jar, there is only a `__cf_bm` cookie being returned from chat.openai.com causing the key error.

Is this approach deprecated at this point?

Please let me know if there is any other info you would like me to grab!

**Comment by daan-dj** [comment]
I have confirmed the issue. it appears openAI has changed the auth flow therefor it needs to be reversed engineered again. I will pick this up ASAP. Will keep you updated.

**Comment by TweedBeetle** [comment]
Hey, any news on on this? Would definitely be worth a coffee or two from me ✌️

**Comment by daan-dj** [comment]
<img width="1238" alt="image" src="https://github.com/daan-dj/TurboGpt/assets/123594600/824b7b0d-6f4f-45ae-a838-a9bcde75c919">


I have just confirmed that the package is still working fine and has always worked fine. I believe chat.openai.com was undergoing heavy loads when this issue was originally opened and therefor you were unable to connect making it look like it was the package its fault.

**Comment by captainmustard** [comment]
I am getting the same error.

```
Starting session...
Traceback (most recent call last):
  File "/home/ian/scripts/TurboGpt-cli/turbogpt-cli.py", line 169, in <module>
    main()
  File "/home/ian/scripts/TurboGpt-cli/turbogpt-cli.py", line 165, in main
    start_session()
  File "/home/ian/scripts/TurboGpt-cli/turbogpt-cli.py", line 82, in start_session
    turbogpt = TurboGpt()
               ^^^^^^^^^^
  File "/home/ian/.local/lib/python3.11/site-packages/turbogpt/turbogpt.py", line 33, in __init__
    self.refresh_puid()
  File "/home/ian/.local/lib/python3.11/site-packages/turbogpt/turbogpt.py", line 43, in refresh_puid
    self.session.cookies["_puid"] = res.cookies["_puid"]
                                    ~~~~~~~~~~~^^^^^^^^^
  File "/home/ian/.local/lib/python3.11/site-packages/tls_client/cookies.py", line 261, in __getitem__
    return self._find_no_duplicates(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/.local/lib/python3.11/site-packages/tls_client/cookies.py", line 340, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='_puid', domain=None, path=None"
```

**Comment by dmackey0** [comment]
Same error also
